language: php
sudo: false
php:
    - 5.5
    - 5.6
    - 7.0
    - nightly
before_install:
    - composer selfupdate
install:
    - export COMPOSER_ROOT_VERSION=dev-master
    - composer update
script:
    - bin/phpspec run --format=pretty